/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema.academico.Vistas;
import javax.swing.*;
import java.awt.event.*;
//import com.mycompany.sistema.academico.Vista.VEstudiantes;
/**
 *
 * @author HP
 */
public class VistaPrincipal extends javax.swing.JFrame {
//private VEstudiantes ventanaEstudiantes;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDatos = new javax.swing.JLabel();
        btnDatosEstudiantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbDatos.setText("INGRESO DE DATOS");

        btnDatosEstudiantes.setText("ESTUDIANTES");
        btnDatosEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosEstudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbDatos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnDatosEstudiantes)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDatos)
                .addGap(51, 51, 51)
                .addComponent(btnDatosEstudiantes)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosEstudiantesActionPerformed
    /*if (ventanaEstudiantes == null) {
        ventanaEstudiantes = new VEstudiantes();
    }
    ventanaEstudiantes.setVisible(true);*/
    }//GEN-LAST:event_btnDatosEstudiantesActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatosEstudiantes;
    private javax.swing.JLabel lbDatos;
    // End of variables declaration//GEN-END:variables
}
